"""add match and timeline tables

Revision ID: 1fc8f5c8693c
Revises: 4da9005b6f61
Create Date: 2026-08-24 00:01:45.119039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fc8f5c8693c'
down_revision: Union[str, Sequence[str], None] = '4da9005b6f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('data_version', sa.String(length=20), nullable=True),
    sa.Column('game_id', sa.BigInteger(), nullable=True),
    sa.Column('game_version', sa.String(length=50), nullable=True),
    sa.Column('game_creation', sa.DateTime(), nullable=True),
    sa.Column('game_start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('game_end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=True),
    sa.Column('game_mode', sa.String(length=30), nullable=True),
    sa.Column('game_type', sa.String(length=30), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.String(length=20), nullable=True),
    sa.Column('end_of_game_result', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_game_version'), 'matches', ['game_version'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.create_index(op.f('ix_matches_platform_id'), 'matches', ['platform_id'], unique=False)
    op.create_index(op.f('ix_matches_queue_id'), 'matches', ['queue_id'], unique=False)
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(length=100), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(length=100), nullable=True),
    sa.Column('champion_level', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('lane', sa.String(length=30), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('total_gold', sa.Integer(), nullable=True),
    sa.Column('gold_earned', sa.Integer(), nullable=True),
    sa.Column('total_minions_killed', sa.Integer(), nullable=True),
    sa.Column('neutral_minions_killed', sa.Integer(), nullable=True),
    sa.Column('total_damage_dealt', sa.Integer(), nullable=True),
    sa.Column('total_damage_dealt_to_champions', sa.Integer(), nullable=True),
    sa.Column('total_damage_taken', sa.Integer(), nullable=True),
    sa.Column('damage_self_mitigated', sa.Integer(), nullable=True),
    sa.Column('physical_damage_dealt_to_champions', sa.Integer(), nullable=True),
    sa.Column('magic_damage_dealt_to_champions', sa.Integer(), nullable=True),
    sa.Column('true_damage_dealt_to_champions', sa.Integer(), nullable=True),
    sa.Column('wards_placed', sa.Integer(), nullable=True),
    sa.Column('wards_killed', sa.Integer(), nullable=True),
    sa.Column('detector_wards_placed', sa.Integer(), nullable=True),
    sa.Column('item_0', sa.Integer(), nullable=True),
    sa.Column('item_1', sa.Integer(), nullable=True),
    sa.Column('item_2', sa.Integer(), nullable=True),
    sa.Column('item_3', sa.Integer(), nullable=True),
    sa.Column('item_4', sa.Integer(), nullable=True),
    sa.Column('item_5', sa.Integer(), nullable=True),
    sa.Column('item_6', sa.Integer(), nullable=True),
    sa.Column('summoner1_id', sa.Integer(), nullable=True),
    sa.Column('summoner2_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'participant_id', name='uq_match_participant')
    )
    op.create_index(op.f('ix_match_participants_champion_id'), 'match_participants', ['champion_id'], unique=False)
    op.create_index(op.f('ix_match_participants_id'), 'match_participants', ['id'], unique=False)
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_puuid'), 'match_participants', ['puuid'], unique=False)
    op.create_index(op.f('ix_match_participants_role'), 'match_participants', ['role'], unique=False)
    op.create_index(op.f('ix_match_participants_team_id'), 'match_participants', ['team_id'], unique=False)
    op.create_table('match_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('first_blood', sa.Boolean(), nullable=True),
    sa.Column('first_tower', sa.Boolean(), nullable=True),
    sa.Column('first_dragon', sa.Boolean(), nullable=True),
    sa.Column('first_baron', sa.Boolean(), nullable=True),
    sa.Column('first_rift_herald', sa.Boolean(), nullable=True),
    sa.Column('first_inhibitor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_team')
    )
    op.create_index(op.f('ix_match_teams_id'), 'match_teams', ['id'], unique=False)
    op.create_index(op.f('ix_match_teams_match_id'), 'match_teams', ['match_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('real_timestamp_ms', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('killer_id', sa.Integer(), nullable=True),
    sa.Column('victim_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_events_match_id'), 'timeline_events', ['match_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_participant_id'), 'timeline_events', ['participant_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_timestamp_ms'), 'timeline_events', ['timestamp_ms'], unique=False)
    op.create_table('timeline_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('current_gold', sa.Integer(), nullable=True),
    sa.Column('total_gold', sa.Integer(), nullable=True),
    sa.Column('gold_per_second', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('minions_killed', sa.Integer(), nullable=True),
    sa.Column('jungle_minions_killed', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('champion_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('damage_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'participant_id', 'timestamp_ms', name='uq_timeline_frame')
    )
    op.create_index(op.f('ix_timeline_frames_id'), 'timeline_frames', ['id'], unique=False)
    op.create_index(op.f('ix_timeline_frames_match_id'), 'timeline_frames', ['match_id'], unique=False)
    op.create_index(op.f('ix_timeline_frames_participant_id'), 'timeline_frames', ['participant_id'], unique=False)
    op.create_index(op.f('ix_timeline_frames_timestamp_ms'), 'timeline_frames', ['timestamp_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_frames_timestamp_ms'), table_name='timeline_frames')
    op.drop_index(op.f('ix_timeline_frames_participant_id'), table_name='timeline_frames')
    op.drop_index(op.f('ix_timeline_frames_match_id'), table_name='timeline_frames')
    op.drop_index(op.f('ix_timeline_frames_id'), table_name='timeline_frames')
    op.drop_table('timeline_frames')
    op.drop_index(op.f('ix_timeline_events_timestamp_ms'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_participant_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_match_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_match_teams_match_id'), table_name='match_teams')
    op.drop_index(op.f('ix_match_teams_id'), table_name='match_teams')
    op.drop_table('match_teams')
    op.drop_index(op.f('ix_match_participants_team_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_role'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_puuid'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_champion_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_matches_queue_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_platform_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_version'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
