"""Create users and riot accounts

Revision ID: 463d4e622f74
Revises: 
Create Date: 2026-08-15 01:10:50.780196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463d4e622f74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('riot_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(length=100), nullable=False),
    sa.Column('game_name', sa.String(length=100), nullable=False),
    sa.Column('tag_line', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riot_accounts_id'), 'riot_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_riot_accounts_puuid'), 'riot_accounts', ['puuid'], unique=True)
    op.create_index(op.f('ix_riot_accounts_user_id'), 'riot_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_riot_accounts_user_id'), table_name='riot_accounts')
    op.drop_index(op.f('ix_riot_accounts_puuid'), table_name='riot_accounts')
    op.drop_index(op.f('ix_riot_accounts_id'), table_name='riot_accounts')
    op.drop_table('riot_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
