"""Add league profile

Revision ID: 4da9005b6f61
Revises: 463d4e622f74
Create Date: 2026-08-15 01:44:27.748854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da9005b6f61'
down_revision: Union[str, Sequence[str], None] = '463d4e622f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riot_account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('summoner_level', sa.Integer(), nullable=True),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['riot_account_id'], ['riot_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_profiles_id'), 'league_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_league_profiles_riot_account_id'), 'league_profiles', ['riot_account_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_profiles_riot_account_id'), table_name='league_profiles')
    op.drop_index(op.f('ix_league_profiles_id'), table_name='league_profiles')
    op.drop_table('league_profiles')
    # ### end Alembic commands ###
